apiVersion: v1
kind: Pod 
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: kistappa/multi-worker
      ports:
        - containerPort: 9999
      

